// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: networking/v1/networking.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	MacAddress    string                 `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Connected     bool                   `protobuf:"varint,4,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_networking_v1_networking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_networking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_networking_v1_networking_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NetworkInterface) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkInterface) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

type WiFiNetwork struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ssid           string                 `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	SignalStrength int32                  `protobuf:"varint,2,opt,name=signal_strength,json=signalStrength,proto3" json:"signal_strength,omitempty"`
	Secured        bool                   `protobuf:"varint,3,opt,name=secured,proto3" json:"secured,omitempty"`
	SecurityType   string                 `protobuf:"bytes,4,opt,name=security_type,json=securityType,proto3" json:"security_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WiFiNetwork) Reset() {
	*x = WiFiNetwork{}
	mi := &file_networking_v1_networking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WiFiNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WiFiNetwork) ProtoMessage() {}

func (x *WiFiNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_networking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WiFiNetwork.ProtoReflect.Descriptor instead.
func (*WiFiNetwork) Descriptor() ([]byte, []int) {
	return file_networking_v1_networking_proto_rawDescGZIP(), []int{1}
}

func (x *WiFiNetwork) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *WiFiNetwork) GetSignalStrength() int32 {
	if x != nil {
		return x.SignalStrength
	}
	return 0
}

func (x *WiFiNetwork) GetSecured() bool {
	if x != nil {
		return x.Secured
	}
	return false
}

func (x *WiFiNetwork) GetSecurityType() string {
	if x != nil {
		return x.SecurityType
	}
	return ""
}

type ListInterfacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterfacesRequest) Reset() {
	*x = ListInterfacesRequest{}
	mi := &file_networking_v1_networking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterfacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfacesRequest) ProtoMessage() {}

func (x *ListInterfacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_networking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterfacesRequest.ProtoReflect.Descriptor instead.
func (*ListInterfacesRequest) Descriptor() ([]byte, []int) {
	return file_networking_v1_networking_proto_rawDescGZIP(), []int{2}
}

type ListInterfacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*NetworkInterface    `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterfacesResponse) Reset() {
	*x = ListInterfacesResponse{}
	mi := &file_networking_v1_networking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterfacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfacesResponse) ProtoMessage() {}

func (x *ListInterfacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_networking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterfacesResponse.ProtoReflect.Descriptor instead.
func (*ListInterfacesResponse) Descriptor() ([]byte, []int) {
	return file_networking_v1_networking_proto_rawDescGZIP(), []int{3}
}

func (x *ListInterfacesResponse) GetInterfaces() []*NetworkInterface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type ScanWiFiNetworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanWiFiNetworksRequest) Reset() {
	*x = ScanWiFiNetworksRequest{}
	mi := &file_networking_v1_networking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanWiFiNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanWiFiNetworksRequest) ProtoMessage() {}

func (x *ScanWiFiNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_networking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanWiFiNetworksRequest.ProtoReflect.Descriptor instead.
func (*ScanWiFiNetworksRequest) Descriptor() ([]byte, []int) {
	return file_networking_v1_networking_proto_rawDescGZIP(), []int{4}
}

type ScanWiFiNetworksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Networks      []*WiFiNetwork         `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanWiFiNetworksResponse) Reset() {
	*x = ScanWiFiNetworksResponse{}
	mi := &file_networking_v1_networking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanWiFiNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanWiFiNetworksResponse) ProtoMessage() {}

func (x *ScanWiFiNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_networking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanWiFiNetworksResponse.ProtoReflect.Descriptor instead.
func (*ScanWiFiNetworksResponse) Descriptor() ([]byte, []int) {
	return file_networking_v1_networking_proto_rawDescGZIP(), []int{5}
}

func (x *ScanWiFiNetworksResponse) GetNetworks() []*WiFiNetwork {
	if x != nil {
		return x.Networks
	}
	return nil
}

type ConnectWiFiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ssid          string                 `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectWiFiRequest) Reset() {
	*x = ConnectWiFiRequest{}
	mi := &file_networking_v1_networking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectWiFiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectWiFiRequest) ProtoMessage() {}

func (x *ConnectWiFiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_networking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectWiFiRequest.ProtoReflect.Descriptor instead.
func (*ConnectWiFiRequest) Descriptor() ([]byte, []int) {
	return file_networking_v1_networking_proto_rawDescGZIP(), []int{6}
}

func (x *ConnectWiFiRequest) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *ConnectWiFiRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ConnectWiFiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectWiFiResponse) Reset() {
	*x = ConnectWiFiResponse{}
	mi := &file_networking_v1_networking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectWiFiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectWiFiResponse) ProtoMessage() {}

func (x *ConnectWiFiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_networking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectWiFiResponse.ProtoReflect.Descriptor instead.
func (*ConnectWiFiResponse) Descriptor() ([]byte, []int) {
	return file_networking_v1_networking_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectWiFiResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectWiFiResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type DisconnectWiFiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ssid          string                 `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectWiFiRequest) Reset() {
	*x = DisconnectWiFiRequest{}
	mi := &file_networking_v1_networking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectWiFiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectWiFiRequest) ProtoMessage() {}

func (x *DisconnectWiFiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_networking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectWiFiRequest.ProtoReflect.Descriptor instead.
func (*DisconnectWiFiRequest) Descriptor() ([]byte, []int) {
	return file_networking_v1_networking_proto_rawDescGZIP(), []int{8}
}

func (x *DisconnectWiFiRequest) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

type DisconnectWiFiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectWiFiResponse) Reset() {
	*x = DisconnectWiFiResponse{}
	mi := &file_networking_v1_networking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectWiFiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectWiFiResponse) ProtoMessage() {}

func (x *DisconnectWiFiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_networking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectWiFiResponse.ProtoReflect.Descriptor instead.
func (*DisconnectWiFiResponse) Descriptor() ([]byte, []int) {
	return file_networking_v1_networking_proto_rawDescGZIP(), []int{9}
}

type GetConnectionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionStatusRequest) Reset() {
	*x = GetConnectionStatusRequest{}
	mi := &file_networking_v1_networking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStatusRequest) ProtoMessage() {}

func (x *GetConnectionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_networking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionStatusRequest) Descriptor() ([]byte, []int) {
	return file_networking_v1_networking_proto_rawDescGZIP(), []int{10}
}

type GetConnectionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	InterfaceName string                 `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Ssid          string                 `protobuf:"bytes,4,opt,name=ssid,proto3" json:"ssid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionStatusResponse) Reset() {
	*x = GetConnectionStatusResponse{}
	mi := &file_networking_v1_networking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStatusResponse) ProtoMessage() {}

func (x *GetConnectionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_networking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionStatusResponse) Descriptor() ([]byte, []int) {
	return file_networking_v1_networking_proto_rawDescGZIP(), []int{11}
}

func (x *GetConnectionStatusResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *GetConnectionStatusResponse) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *GetConnectionStatusResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *GetConnectionStatusResponse) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

var File_networking_v1_networking_proto protoreflect.FileDescriptor

const file_networking_v1_networking_proto_rawDesc = "" +
	"\n" +
	"\x1enetworking/v1/networking.proto\x12\x14fontis.networking.v1\"y\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\x12\x1c\n" +
	"\tconnected\x18\x04 \x01(\bR\tconnected\"\x89\x01\n" +
	"\vWiFiNetwork\x12\x12\n" +
	"\x04ssid\x18\x01 \x01(\tR\x04ssid\x12'\n" +
	"\x0fsignal_strength\x18\x02 \x01(\x05R\x0esignalStrength\x12\x18\n" +
	"\asecured\x18\x03 \x01(\bR\asecured\x12#\n" +
	"\rsecurity_type\x18\x04 \x01(\tR\fsecurityType\"\x17\n" +
	"\x15ListInterfacesRequest\"`\n" +
	"\x16ListInterfacesResponse\x12F\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2&.fontis.networking.v1.NetworkInterfaceR\n" +
	"interfaces\"\x19\n" +
	"\x17ScanWiFiNetworksRequest\"Y\n" +
	"\x18ScanWiFiNetworksResponse\x12=\n" +
	"\bnetworks\x18\x01 \x03(\v2!.fontis.networking.v1.WiFiNetworkR\bnetworks\"D\n" +
	"\x12ConnectWiFiRequest\x12\x12\n" +
	"\x04ssid\x18\x01 \x01(\tR\x04ssid\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"N\n" +
	"\x13ConnectWiFiResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\"+\n" +
	"\x15DisconnectWiFiRequest\x12\x12\n" +
	"\x04ssid\x18\x01 \x01(\tR\x04ssid\"\x18\n" +
	"\x16DisconnectWiFiResponse\"\x1c\n" +
	"\x1aGetConnectionStatusRequest\"\x95\x01\n" +
	"\x1bGetConnectionStatusResponse\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04ssid\x18\x04 \x01(\tR\x04ssid2\xc0\x04\n" +
	"\x11NetworkingService\x12k\n" +
	"\x0eListInterfaces\x12+.fontis.networking.v1.ListInterfacesRequest\x1a,.fontis.networking.v1.ListInterfacesResponse\x12q\n" +
	"\x10ScanWiFiNetworks\x12-.fontis.networking.v1.ScanWiFiNetworksRequest\x1a..fontis.networking.v1.ScanWiFiNetworksResponse\x12b\n" +
	"\vConnectWiFi\x12(.fontis.networking.v1.ConnectWiFiRequest\x1a).fontis.networking.v1.ConnectWiFiResponse\x12k\n" +
	"\x0eDisconnectWiFi\x12+.fontis.networking.v1.DisconnectWiFiRequest\x1a,.fontis.networking.v1.DisconnectWiFiResponse\x12z\n" +
	"\x13GetConnectionStatus\x120.fontis.networking.v1.GetConnectionStatusRequest\x1a1.fontis.networking.v1.GetConnectionStatusResponseB@Z>github.com/fontis-dev/fontis-platform/runtime/networking/protob\x06proto3"

var (
	file_networking_v1_networking_proto_rawDescOnce sync.Once
	file_networking_v1_networking_proto_rawDescData []byte
)

func file_networking_v1_networking_proto_rawDescGZIP() []byte {
	file_networking_v1_networking_proto_rawDescOnce.Do(func() {
		file_networking_v1_networking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networking_v1_networking_proto_rawDesc), len(file_networking_v1_networking_proto_rawDesc)))
	})
	return file_networking_v1_networking_proto_rawDescData
}

var file_networking_v1_networking_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_networking_v1_networking_proto_goTypes = []any{
	(*NetworkInterface)(nil),            // 0: fontis.networking.v1.NetworkInterface
	(*WiFiNetwork)(nil),                 // 1: fontis.networking.v1.WiFiNetwork
	(*ListInterfacesRequest)(nil),       // 2: fontis.networking.v1.ListInterfacesRequest
	(*ListInterfacesResponse)(nil),      // 3: fontis.networking.v1.ListInterfacesResponse
	(*ScanWiFiNetworksRequest)(nil),     // 4: fontis.networking.v1.ScanWiFiNetworksRequest
	(*ScanWiFiNetworksResponse)(nil),    // 5: fontis.networking.v1.ScanWiFiNetworksResponse
	(*ConnectWiFiRequest)(nil),          // 6: fontis.networking.v1.ConnectWiFiRequest
	(*ConnectWiFiResponse)(nil),         // 7: fontis.networking.v1.ConnectWiFiResponse
	(*DisconnectWiFiRequest)(nil),       // 8: fontis.networking.v1.DisconnectWiFiRequest
	(*DisconnectWiFiResponse)(nil),      // 9: fontis.networking.v1.DisconnectWiFiResponse
	(*GetConnectionStatusRequest)(nil),  // 10: fontis.networking.v1.GetConnectionStatusRequest
	(*GetConnectionStatusResponse)(nil), // 11: fontis.networking.v1.GetConnectionStatusResponse
}
var file_networking_v1_networking_proto_depIdxs = []int32{
	0,  // 0: fontis.networking.v1.ListInterfacesResponse.interfaces:type_name -> fontis.networking.v1.NetworkInterface
	1,  // 1: fontis.networking.v1.ScanWiFiNetworksResponse.networks:type_name -> fontis.networking.v1.WiFiNetwork
	2,  // 2: fontis.networking.v1.NetworkingService.ListInterfaces:input_type -> fontis.networking.v1.ListInterfacesRequest
	4,  // 3: fontis.networking.v1.NetworkingService.ScanWiFiNetworks:input_type -> fontis.networking.v1.ScanWiFiNetworksRequest
	6,  // 4: fontis.networking.v1.NetworkingService.ConnectWiFi:input_type -> fontis.networking.v1.ConnectWiFiRequest
	8,  // 5: fontis.networking.v1.NetworkingService.DisconnectWiFi:input_type -> fontis.networking.v1.DisconnectWiFiRequest
	10, // 6: fontis.networking.v1.NetworkingService.GetConnectionStatus:input_type -> fontis.networking.v1.GetConnectionStatusRequest
	3,  // 7: fontis.networking.v1.NetworkingService.ListInterfaces:output_type -> fontis.networking.v1.ListInterfacesResponse
	5,  // 8: fontis.networking.v1.NetworkingService.ScanWiFiNetworks:output_type -> fontis.networking.v1.ScanWiFiNetworksResponse
	7,  // 9: fontis.networking.v1.NetworkingService.ConnectWiFi:output_type -> fontis.networking.v1.ConnectWiFiResponse
	9,  // 10: fontis.networking.v1.NetworkingService.DisconnectWiFi:output_type -> fontis.networking.v1.DisconnectWiFiResponse
	11, // 11: fontis.networking.v1.NetworkingService.GetConnectionStatus:output_type -> fontis.networking.v1.GetConnectionStatusResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_networking_v1_networking_proto_init() }
func file_networking_v1_networking_proto_init() {
	if File_networking_v1_networking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networking_v1_networking_proto_rawDesc), len(file_networking_v1_networking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_networking_v1_networking_proto_goTypes,
		DependencyIndexes: file_networking_v1_networking_proto_depIdxs,
		MessageInfos:      file_networking_v1_networking_proto_msgTypes,
	}.Build()
	File_networking_v1_networking_proto = out.File
	file_networking_v1_networking_proto_goTypes = nil
	file_networking_v1_networking_proto_depIdxs = nil
}
