// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: networking/v1/networking.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkingService_ListInterfaces_FullMethodName      = "/fontis.networking.v1.NetworkingService/ListInterfaces"
	NetworkingService_ScanWiFiNetworks_FullMethodName    = "/fontis.networking.v1.NetworkingService/ScanWiFiNetworks"
	NetworkingService_ConnectWiFi_FullMethodName         = "/fontis.networking.v1.NetworkingService/ConnectWiFi"
	NetworkingService_DisconnectWiFi_FullMethodName      = "/fontis.networking.v1.NetworkingService/DisconnectWiFi"
	NetworkingService_GetConnectionStatus_FullMethodName = "/fontis.networking.v1.NetworkingService/GetConnectionStatus"
)

// NetworkingServiceClient is the client API for NetworkingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkingServiceClient interface {
	ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error)
	ScanWiFiNetworks(ctx context.Context, in *ScanWiFiNetworksRequest, opts ...grpc.CallOption) (*ScanWiFiNetworksResponse, error)
	ConnectWiFi(ctx context.Context, in *ConnectWiFiRequest, opts ...grpc.CallOption) (*ConnectWiFiResponse, error)
	DisconnectWiFi(ctx context.Context, in *DisconnectWiFiRequest, opts ...grpc.CallOption) (*DisconnectWiFiResponse, error)
	GetConnectionStatus(ctx context.Context, in *GetConnectionStatusRequest, opts ...grpc.CallOption) (*GetConnectionStatusResponse, error)
}

type networkingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkingServiceClient(cc grpc.ClientConnInterface) NetworkingServiceClient {
	return &networkingServiceClient{cc}
}

func (c *networkingServiceClient) ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInterfacesResponse)
	err := c.cc.Invoke(ctx, NetworkingService_ListInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkingServiceClient) ScanWiFiNetworks(ctx context.Context, in *ScanWiFiNetworksRequest, opts ...grpc.CallOption) (*ScanWiFiNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanWiFiNetworksResponse)
	err := c.cc.Invoke(ctx, NetworkingService_ScanWiFiNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkingServiceClient) ConnectWiFi(ctx context.Context, in *ConnectWiFiRequest, opts ...grpc.CallOption) (*ConnectWiFiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectWiFiResponse)
	err := c.cc.Invoke(ctx, NetworkingService_ConnectWiFi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkingServiceClient) DisconnectWiFi(ctx context.Context, in *DisconnectWiFiRequest, opts ...grpc.CallOption) (*DisconnectWiFiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectWiFiResponse)
	err := c.cc.Invoke(ctx, NetworkingService_DisconnectWiFi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkingServiceClient) GetConnectionStatus(ctx context.Context, in *GetConnectionStatusRequest, opts ...grpc.CallOption) (*GetConnectionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectionStatusResponse)
	err := c.cc.Invoke(ctx, NetworkingService_GetConnectionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkingServiceServer is the server API for NetworkingService service.
// All implementations must embed UnimplementedNetworkingServiceServer
// for forward compatibility.
type NetworkingServiceServer interface {
	ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error)
	ScanWiFiNetworks(context.Context, *ScanWiFiNetworksRequest) (*ScanWiFiNetworksResponse, error)
	ConnectWiFi(context.Context, *ConnectWiFiRequest) (*ConnectWiFiResponse, error)
	DisconnectWiFi(context.Context, *DisconnectWiFiRequest) (*DisconnectWiFiResponse, error)
	GetConnectionStatus(context.Context, *GetConnectionStatusRequest) (*GetConnectionStatusResponse, error)
	mustEmbedUnimplementedNetworkingServiceServer()
}

// UnimplementedNetworkingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkingServiceServer struct{}

func (UnimplementedNetworkingServiceServer) ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInterfaces not implemented")
}
func (UnimplementedNetworkingServiceServer) ScanWiFiNetworks(context.Context, *ScanWiFiNetworksRequest) (*ScanWiFiNetworksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanWiFiNetworks not implemented")
}
func (UnimplementedNetworkingServiceServer) ConnectWiFi(context.Context, *ConnectWiFiRequest) (*ConnectWiFiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectWiFi not implemented")
}
func (UnimplementedNetworkingServiceServer) DisconnectWiFi(context.Context, *DisconnectWiFiRequest) (*DisconnectWiFiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectWiFi not implemented")
}
func (UnimplementedNetworkingServiceServer) GetConnectionStatus(context.Context, *GetConnectionStatusRequest) (*GetConnectionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectionStatus not implemented")
}
func (UnimplementedNetworkingServiceServer) mustEmbedUnimplementedNetworkingServiceServer() {}
func (UnimplementedNetworkingServiceServer) testEmbeddedByValue()                           {}

// UnsafeNetworkingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkingServiceServer will
// result in compilation errors.
type UnsafeNetworkingServiceServer interface {
	mustEmbedUnimplementedNetworkingServiceServer()
}

func RegisterNetworkingServiceServer(s grpc.ServiceRegistrar, srv NetworkingServiceServer) {
	// If the following call panics, it indicates UnimplementedNetworkingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkingService_ServiceDesc, srv)
}

func _NetworkingService_ListInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkingServiceServer).ListInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkingService_ListInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkingServiceServer).ListInterfaces(ctx, req.(*ListInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkingService_ScanWiFiNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanWiFiNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkingServiceServer).ScanWiFiNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkingService_ScanWiFiNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkingServiceServer).ScanWiFiNetworks(ctx, req.(*ScanWiFiNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkingService_ConnectWiFi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectWiFiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkingServiceServer).ConnectWiFi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkingService_ConnectWiFi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkingServiceServer).ConnectWiFi(ctx, req.(*ConnectWiFiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkingService_DisconnectWiFi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectWiFiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkingServiceServer).DisconnectWiFi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkingService_DisconnectWiFi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkingServiceServer).DisconnectWiFi(ctx, req.(*DisconnectWiFiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkingService_GetConnectionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkingServiceServer).GetConnectionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkingService_GetConnectionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkingServiceServer).GetConnectionStatus(ctx, req.(*GetConnectionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkingService_ServiceDesc is the grpc.ServiceDesc for NetworkingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fontis.networking.v1.NetworkingService",
	HandlerType: (*NetworkingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInterfaces",
			Handler:    _NetworkingService_ListInterfaces_Handler,
		},
		{
			MethodName: "ScanWiFiNetworks",
			Handler:    _NetworkingService_ScanWiFiNetworks_Handler,
		},
		{
			MethodName: "ConnectWiFi",
			Handler:    _NetworkingService_ConnectWiFi_Handler,
		},
		{
			MethodName: "DisconnectWiFi",
			Handler:    _NetworkingService_DisconnectWiFi_Handler,
		},
		{
			MethodName: "GetConnectionStatus",
			Handler:    _NetworkingService_GetConnectionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "networking/v1/networking.proto",
}
