// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: storage/v1/storage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Removable     bool                   `protobuf:"varint,4,opt,name=removable,proto3" json:"removable,omitempty"`
	Encrypted     bool                   `protobuf:"varint,5,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockDevice) Reset() {
	*x = BlockDevice{}
	mi := &file_storage_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDevice) ProtoMessage() {}

func (x *BlockDevice) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDevice.ProtoReflect.Descriptor instead.
func (*BlockDevice) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *BlockDevice) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BlockDevice) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *BlockDevice) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BlockDevice) GetRemovable() bool {
	if x != nil {
		return x.Removable
	}
	return false
}

func (x *BlockDevice) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MountPath     string                 `protobuf:"bytes,4,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	Encrypted     bool                   `protobuf:"varint,5,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_storage_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *Volume) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Volume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Volume) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Volume) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *Volume) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

func (x *Volume) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{2}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*BlockDevice         `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{3}
}

func (x *ListDevicesResponse) GetDevices() []*BlockDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type CreateVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DevicePath    string                 `protobuf:"bytes,2,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Encrypt       bool                   `protobuf:"varint,4,opt,name=encrypt,proto3" json:"encrypt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeRequest) Reset() {
	*x = CreateVolumeRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeRequest) ProtoMessage() {}

func (x *CreateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVolumeRequest) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

func (x *CreateVolumeRequest) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateVolumeRequest) GetEncrypt() bool {
	if x != nil {
		return x.Encrypt
	}
	return false
}

type CreateVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        *Volume                `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeResponse) Reset() {
	*x = CreateVolumeResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeResponse) ProtoMessage() {}

func (x *CreateVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeResponse.ProtoReflect.Descriptor instead.
func (*CreateVolumeResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{5}
}

func (x *CreateVolumeResponse) GetVolume() *Volume {
	if x != nil {
		return x.Volume
	}
	return nil
}

type MountVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	MountPath     string                 `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountVolumeRequest) Reset() {
	*x = MountVolumeRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountVolumeRequest) ProtoMessage() {}

func (x *MountVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountVolumeRequest.ProtoReflect.Descriptor instead.
func (*MountVolumeRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{6}
}

func (x *MountVolumeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *MountVolumeRequest) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

type MountVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        *Volume                `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountVolumeResponse) Reset() {
	*x = MountVolumeResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountVolumeResponse) ProtoMessage() {}

func (x *MountVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountVolumeResponse.ProtoReflect.Descriptor instead.
func (*MountVolumeResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{7}
}

func (x *MountVolumeResponse) GetVolume() *Volume {
	if x != nil {
		return x.Volume
	}
	return nil
}

type UnmountVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountVolumeRequest) Reset() {
	*x = UnmountVolumeRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountVolumeRequest) ProtoMessage() {}

func (x *UnmountVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountVolumeRequest.ProtoReflect.Descriptor instead.
func (*UnmountVolumeRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{8}
}

func (x *UnmountVolumeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type UnmountVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountVolumeResponse) Reset() {
	*x = UnmountVolumeResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountVolumeResponse) ProtoMessage() {}

func (x *UnmountVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountVolumeResponse.ProtoReflect.Descriptor instead.
func (*UnmountVolumeResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{9}
}

type ListVolumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesRequest) Reset() {
	*x = ListVolumesRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesRequest) ProtoMessage() {}

func (x *ListVolumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesRequest.ProtoReflect.Descriptor instead.
func (*ListVolumesRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{10}
}

type ListVolumesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*Volume              `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesResponse) Reset() {
	*x = ListVolumesResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesResponse) ProtoMessage() {}

func (x *ListVolumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesResponse.ProtoReflect.Descriptor instead.
func (*ListVolumesResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{11}
}

func (x *ListVolumesResponse) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type DeleteVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeRequest) Reset() {
	*x = DeleteVolumeRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeRequest) ProtoMessage() {}

func (x *DeleteVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeRequest.ProtoReflect.Descriptor instead.
func (*DeleteVolumeRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteVolumeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type DeleteVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeResponse) Reset() {
	*x = DeleteVolumeResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeResponse) ProtoMessage() {}

func (x *DeleteVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeResponse.ProtoReflect.Descriptor instead.
func (*DeleteVolumeResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{13}
}

type GetVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumeRequest) Reset() {
	*x = GetVolumeRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeRequest) ProtoMessage() {}

func (x *GetVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeRequest.ProtoReflect.Descriptor instead.
func (*GetVolumeRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{14}
}

func (x *GetVolumeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type GetVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        *Volume                `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumeResponse) Reset() {
	*x = GetVolumeResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeResponse) ProtoMessage() {}

func (x *GetVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeResponse.ProtoReflect.Descriptor instead.
func (*GetVolumeResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{15}
}

func (x *GetVolumeResponse) GetVolume() *Volume {
	if x != nil {
		return x.Volume
	}
	return nil
}

var File_storage_v1_storage_proto protoreflect.FileDescriptor

const file_storage_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x18storage/v1/storage.proto\x12\x11fontis.storage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x01\n" +
	"\vBlockDevice\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\x1c\n" +
	"\tremovable\x18\x04 \x01(\bR\tremovable\x12\x1c\n" +
	"\tencrypted\x18\x05 \x01(\bR\tencrypted\"\xc3\x01\n" +
	"\x06Volume\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x04 \x01(\tR\tmountPath\x12\x1c\n" +
	"\tencrypted\x18\x05 \x01(\bR\tencrypted\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x14\n" +
	"\x12ListDevicesRequest\"O\n" +
	"\x13ListDevicesResponse\x128\n" +
	"\adevices\x18\x01 \x03(\v2\x1e.fontis.storage.v1.BlockDeviceR\adevices\"\x83\x01\n" +
	"\x13CreateVolumeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vdevice_path\x18\x02 \x01(\tR\n" +
	"devicePath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\x18\n" +
	"\aencrypt\x18\x04 \x01(\bR\aencrypt\"I\n" +
	"\x14CreateVolumeResponse\x121\n" +
	"\x06volume\x18\x01 \x01(\v2\x19.fontis.storage.v1.VolumeR\x06volume\"P\n" +
	"\x12MountVolumeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\"H\n" +
	"\x13MountVolumeResponse\x121\n" +
	"\x06volume\x18\x01 \x01(\v2\x19.fontis.storage.v1.VolumeR\x06volume\"3\n" +
	"\x14UnmountVolumeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\"\x17\n" +
	"\x15UnmountVolumeResponse\"\x14\n" +
	"\x12ListVolumesRequest\"J\n" +
	"\x13ListVolumesResponse\x123\n" +
	"\avolumes\x18\x01 \x03(\v2\x19.fontis.storage.v1.VolumeR\avolumes\"2\n" +
	"\x13DeleteVolumeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\"\x16\n" +
	"\x14DeleteVolumeResponse\"/\n" +
	"\x10GetVolumeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\"F\n" +
	"\x11GetVolumeResponse\x121\n" +
	"\x06volume\x18\x01 \x01(\v2\x19.fontis.storage.v1.VolumeR\x06volume2\xa8\x05\n" +
	"\x0eStorageService\x12\\\n" +
	"\vListDevices\x12%.fontis.storage.v1.ListDevicesRequest\x1a&.fontis.storage.v1.ListDevicesResponse\x12_\n" +
	"\fCreateVolume\x12&.fontis.storage.v1.CreateVolumeRequest\x1a'.fontis.storage.v1.CreateVolumeResponse\x12V\n" +
	"\tGetVolume\x12#.fontis.storage.v1.GetVolumeRequest\x1a$.fontis.storage.v1.GetVolumeResponse\x12\\\n" +
	"\vMountVolume\x12%.fontis.storage.v1.MountVolumeRequest\x1a&.fontis.storage.v1.MountVolumeResponse\x12b\n" +
	"\rUnmountVolume\x12'.fontis.storage.v1.UnmountVolumeRequest\x1a(.fontis.storage.v1.UnmountVolumeResponse\x12\\\n" +
	"\vListVolumes\x12%.fontis.storage.v1.ListVolumesRequest\x1a&.fontis.storage.v1.ListVolumesResponse\x12_\n" +
	"\fDeleteVolume\x12&.fontis.storage.v1.DeleteVolumeRequest\x1a'.fontis.storage.v1.DeleteVolumeResponseB=Z;github.com/fontis-dev/fontis-platform/runtime/storage/protob\x06proto3"

var (
	file_storage_v1_storage_proto_rawDescOnce sync.Once
	file_storage_v1_storage_proto_rawDescData []byte
)

func file_storage_v1_storage_proto_rawDescGZIP() []byte {
	file_storage_v1_storage_proto_rawDescOnce.Do(func() {
		file_storage_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_v1_storage_proto_rawDesc), len(file_storage_v1_storage_proto_rawDesc)))
	})
	return file_storage_v1_storage_proto_rawDescData
}

var file_storage_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_storage_v1_storage_proto_goTypes = []any{
	(*BlockDevice)(nil),           // 0: fontis.storage.v1.BlockDevice
	(*Volume)(nil),                // 1: fontis.storage.v1.Volume
	(*ListDevicesRequest)(nil),    // 2: fontis.storage.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),   // 3: fontis.storage.v1.ListDevicesResponse
	(*CreateVolumeRequest)(nil),   // 4: fontis.storage.v1.CreateVolumeRequest
	(*CreateVolumeResponse)(nil),  // 5: fontis.storage.v1.CreateVolumeResponse
	(*MountVolumeRequest)(nil),    // 6: fontis.storage.v1.MountVolumeRequest
	(*MountVolumeResponse)(nil),   // 7: fontis.storage.v1.MountVolumeResponse
	(*UnmountVolumeRequest)(nil),  // 8: fontis.storage.v1.UnmountVolumeRequest
	(*UnmountVolumeResponse)(nil), // 9: fontis.storage.v1.UnmountVolumeResponse
	(*ListVolumesRequest)(nil),    // 10: fontis.storage.v1.ListVolumesRequest
	(*ListVolumesResponse)(nil),   // 11: fontis.storage.v1.ListVolumesResponse
	(*DeleteVolumeRequest)(nil),   // 12: fontis.storage.v1.DeleteVolumeRequest
	(*DeleteVolumeResponse)(nil),  // 13: fontis.storage.v1.DeleteVolumeResponse
	(*GetVolumeRequest)(nil),      // 14: fontis.storage.v1.GetVolumeRequest
	(*GetVolumeResponse)(nil),     // 15: fontis.storage.v1.GetVolumeResponse
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_storage_v1_storage_proto_depIdxs = []int32{
	16, // 0: fontis.storage.v1.Volume.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: fontis.storage.v1.ListDevicesResponse.devices:type_name -> fontis.storage.v1.BlockDevice
	1,  // 2: fontis.storage.v1.CreateVolumeResponse.volume:type_name -> fontis.storage.v1.Volume
	1,  // 3: fontis.storage.v1.MountVolumeResponse.volume:type_name -> fontis.storage.v1.Volume
	1,  // 4: fontis.storage.v1.ListVolumesResponse.volumes:type_name -> fontis.storage.v1.Volume
	1,  // 5: fontis.storage.v1.GetVolumeResponse.volume:type_name -> fontis.storage.v1.Volume
	2,  // 6: fontis.storage.v1.StorageService.ListDevices:input_type -> fontis.storage.v1.ListDevicesRequest
	4,  // 7: fontis.storage.v1.StorageService.CreateVolume:input_type -> fontis.storage.v1.CreateVolumeRequest
	14, // 8: fontis.storage.v1.StorageService.GetVolume:input_type -> fontis.storage.v1.GetVolumeRequest
	6,  // 9: fontis.storage.v1.StorageService.MountVolume:input_type -> fontis.storage.v1.MountVolumeRequest
	8,  // 10: fontis.storage.v1.StorageService.UnmountVolume:input_type -> fontis.storage.v1.UnmountVolumeRequest
	10, // 11: fontis.storage.v1.StorageService.ListVolumes:input_type -> fontis.storage.v1.ListVolumesRequest
	12, // 12: fontis.storage.v1.StorageService.DeleteVolume:input_type -> fontis.storage.v1.DeleteVolumeRequest
	3,  // 13: fontis.storage.v1.StorageService.ListDevices:output_type -> fontis.storage.v1.ListDevicesResponse
	5,  // 14: fontis.storage.v1.StorageService.CreateVolume:output_type -> fontis.storage.v1.CreateVolumeResponse
	15, // 15: fontis.storage.v1.StorageService.GetVolume:output_type -> fontis.storage.v1.GetVolumeResponse
	7,  // 16: fontis.storage.v1.StorageService.MountVolume:output_type -> fontis.storage.v1.MountVolumeResponse
	9,  // 17: fontis.storage.v1.StorageService.UnmountVolume:output_type -> fontis.storage.v1.UnmountVolumeResponse
	11, // 18: fontis.storage.v1.StorageService.ListVolumes:output_type -> fontis.storage.v1.ListVolumesResponse
	13, // 19: fontis.storage.v1.StorageService.DeleteVolume:output_type -> fontis.storage.v1.DeleteVolumeResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_storage_v1_storage_proto_init() }
func file_storage_v1_storage_proto_init() {
	if File_storage_v1_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_v1_storage_proto_rawDesc), len(file_storage_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_v1_storage_proto_goTypes,
		DependencyIndexes: file_storage_v1_storage_proto_depIdxs,
		MessageInfos:      file_storage_v1_storage_proto_msgTypes,
	}.Build()
	File_storage_v1_storage_proto = out.File
	file_storage_v1_storage_proto_goTypes = nil
	file_storage_v1_storage_proto_depIdxs = nil
}
