// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: identity/v1/identity.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Household struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Household) Reset() {
	*x = Household{}
	mi := &file_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Household) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Household) ProtoMessage() {}

func (x *Household) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Household.ProtoReflect.Descriptor instead.
func (*Household) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *Household) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Household) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Household) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Household) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HouseholdId   string                 `protobuf:"bytes,2,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *Profile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profile) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

func (x *Profile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Profile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Profile) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Profile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Profile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateHouseholdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHouseholdRequest) Reset() {
	*x = CreateHouseholdRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHouseholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHouseholdRequest) ProtoMessage() {}

func (x *CreateHouseholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHouseholdRequest.ProtoReflect.Descriptor instead.
func (*CreateHouseholdRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHouseholdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateHouseholdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Household     *Household             `protobuf:"bytes,1,opt,name=household,proto3" json:"household,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHouseholdResponse) Reset() {
	*x = CreateHouseholdResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHouseholdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHouseholdResponse) ProtoMessage() {}

func (x *CreateHouseholdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHouseholdResponse.ProtoReflect.Descriptor instead.
func (*CreateHouseholdResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *CreateHouseholdResponse) GetHousehold() *Household {
	if x != nil {
		return x.Household
	}
	return nil
}

type GetHouseholdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseholdId   string                 `protobuf:"bytes,1,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseholdRequest) Reset() {
	*x = GetHouseholdRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseholdRequest) ProtoMessage() {}

func (x *GetHouseholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseholdRequest.ProtoReflect.Descriptor instead.
func (*GetHouseholdRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *GetHouseholdRequest) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

type GetHouseholdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Household     *Household             `protobuf:"bytes,1,opt,name=household,proto3" json:"household,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseholdResponse) Reset() {
	*x = GetHouseholdResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseholdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseholdResponse) ProtoMessage() {}

func (x *GetHouseholdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseholdResponse.ProtoReflect.Descriptor instead.
func (*GetHouseholdResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *GetHouseholdResponse) GetHousehold() *Household {
	if x != nil {
		return x.Household
	}
	return nil
}

type UpdateHouseholdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseholdId   string                 `protobuf:"bytes,1,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHouseholdRequest) Reset() {
	*x = UpdateHouseholdRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHouseholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHouseholdRequest) ProtoMessage() {}

func (x *UpdateHouseholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHouseholdRequest.ProtoReflect.Descriptor instead.
func (*UpdateHouseholdRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateHouseholdRequest) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

func (x *UpdateHouseholdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateHouseholdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Household     *Household             `protobuf:"bytes,1,opt,name=household,proto3" json:"household,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHouseholdResponse) Reset() {
	*x = UpdateHouseholdResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHouseholdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHouseholdResponse) ProtoMessage() {}

func (x *UpdateHouseholdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHouseholdResponse.ProtoReflect.Descriptor instead.
func (*UpdateHouseholdResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateHouseholdResponse) GetHousehold() *Household {
	if x != nil {
		return x.Household
	}
	return nil
}

type DeleteHouseholdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseholdId   string                 `protobuf:"bytes,1,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHouseholdRequest) Reset() {
	*x = DeleteHouseholdRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHouseholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHouseholdRequest) ProtoMessage() {}

func (x *DeleteHouseholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHouseholdRequest.ProtoReflect.Descriptor instead.
func (*DeleteHouseholdRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteHouseholdRequest) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

type DeleteHouseholdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHouseholdResponse) Reset() {
	*x = DeleteHouseholdResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHouseholdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHouseholdResponse) ProtoMessage() {}

func (x *DeleteHouseholdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHouseholdResponse.ProtoReflect.Descriptor instead.
func (*DeleteHouseholdResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{9}
}

type ListHouseholdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHouseholdsRequest) Reset() {
	*x = ListHouseholdsRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHouseholdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHouseholdsRequest) ProtoMessage() {}

func (x *ListHouseholdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHouseholdsRequest.ProtoReflect.Descriptor instead.
func (*ListHouseholdsRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{10}
}

type ListHouseholdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Households    []*Household           `protobuf:"bytes,1,rep,name=households,proto3" json:"households,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHouseholdsResponse) Reset() {
	*x = ListHouseholdsResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHouseholdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHouseholdsResponse) ProtoMessage() {}

func (x *ListHouseholdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHouseholdsResponse.ProtoReflect.Descriptor instead.
func (*ListHouseholdsResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{11}
}

func (x *ListHouseholdsResponse) GetHouseholds() []*Household {
	if x != nil {
		return x.Households
	}
	return nil
}

type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseholdId   string                 `protobuf:"bytes,1,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{12}
}

func (x *CreateProfileRequest) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

func (x *CreateProfileRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateProfileRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{13}
}

func (x *CreateProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{14}
}

func (x *GetProfileRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{15}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseholdId   string                 `protobuf:"bytes,1,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{16}
}

func (x *ListProfilesRequest) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{17}
}

func (x *ListProfilesResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateProfileRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *UpdateProfileRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateProfileRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type DeleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteProfileRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type DeleteProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileResponse) Reset() {
	*x = DeleteProfileResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileResponse) ProtoMessage() {}

func (x *DeleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{21}
}

var File_identity_v1_identity_proto protoreflect.FileDescriptor

const file_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x1aidentity/v1/identity.proto\x12\x12fontis.identity.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x01\n" +
	"\tHousehold\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x88\x02\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fhousehold_id\x18\x02 \x01(\tR\vhouseholdId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\",\n" +
	"\x16CreateHouseholdRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"V\n" +
	"\x17CreateHouseholdResponse\x12;\n" +
	"\thousehold\x18\x01 \x01(\v2\x1d.fontis.identity.v1.HouseholdR\thousehold\"8\n" +
	"\x13GetHouseholdRequest\x12!\n" +
	"\fhousehold_id\x18\x01 \x01(\tR\vhouseholdId\"S\n" +
	"\x14GetHouseholdResponse\x12;\n" +
	"\thousehold\x18\x01 \x01(\v2\x1d.fontis.identity.v1.HouseholdR\thousehold\"O\n" +
	"\x16UpdateHouseholdRequest\x12!\n" +
	"\fhousehold_id\x18\x01 \x01(\tR\vhouseholdId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"V\n" +
	"\x17UpdateHouseholdResponse\x12;\n" +
	"\thousehold\x18\x01 \x01(\v2\x1d.fontis.identity.v1.HouseholdR\thousehold\";\n" +
	"\x16DeleteHouseholdRequest\x12!\n" +
	"\fhousehold_id\x18\x01 \x01(\tR\vhouseholdId\"\x19\n" +
	"\x17DeleteHouseholdResponse\"\x17\n" +
	"\x15ListHouseholdsRequest\"W\n" +
	"\x16ListHouseholdsResponse\x12=\n" +
	"\n" +
	"households\x18\x01 \x03(\v2\x1d.fontis.identity.v1.HouseholdR\n" +
	"households\"p\n" +
	"\x14CreateProfileRequest\x12!\n" +
	"\fhousehold_id\x18\x01 \x01(\tR\vhouseholdId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"N\n" +
	"\x15CreateProfileResponse\x125\n" +
	"\aprofile\x18\x01 \x01(\v2\x1b.fontis.identity.v1.ProfileR\aprofile\"2\n" +
	"\x11GetProfileRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"K\n" +
	"\x12GetProfileResponse\x125\n" +
	"\aprofile\x18\x01 \x01(\v2\x1b.fontis.identity.v1.ProfileR\aprofile\"8\n" +
	"\x13ListProfilesRequest\x12!\n" +
	"\fhousehold_id\x18\x01 \x01(\tR\vhouseholdId\"O\n" +
	"\x14ListProfilesResponse\x127\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1b.fontis.identity.v1.ProfileR\bprofiles\"l\n" +
	"\x14UpdateProfileRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"N\n" +
	"\x15UpdateProfileResponse\x125\n" +
	"\aprofile\x18\x01 \x01(\v2\x1b.fontis.identity.v1.ProfileR\aprofile\"5\n" +
	"\x14DeleteProfileRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"\x17\n" +
	"\x15DeleteProfileResponse2\x93\b\n" +
	"\x0fIdentityService\x12j\n" +
	"\x0fCreateHousehold\x12*.fontis.identity.v1.CreateHouseholdRequest\x1a+.fontis.identity.v1.CreateHouseholdResponse\x12a\n" +
	"\fGetHousehold\x12'.fontis.identity.v1.GetHouseholdRequest\x1a(.fontis.identity.v1.GetHouseholdResponse\x12j\n" +
	"\x0fUpdateHousehold\x12*.fontis.identity.v1.UpdateHouseholdRequest\x1a+.fontis.identity.v1.UpdateHouseholdResponse\x12j\n" +
	"\x0fDeleteHousehold\x12*.fontis.identity.v1.DeleteHouseholdRequest\x1a+.fontis.identity.v1.DeleteHouseholdResponse\x12g\n" +
	"\x0eListHouseholds\x12).fontis.identity.v1.ListHouseholdsRequest\x1a*.fontis.identity.v1.ListHouseholdsResponse\x12d\n" +
	"\rCreateProfile\x12(.fontis.identity.v1.CreateProfileRequest\x1a).fontis.identity.v1.CreateProfileResponse\x12[\n" +
	"\n" +
	"GetProfile\x12%.fontis.identity.v1.GetProfileRequest\x1a&.fontis.identity.v1.GetProfileResponse\x12a\n" +
	"\fListProfiles\x12'.fontis.identity.v1.ListProfilesRequest\x1a(.fontis.identity.v1.ListProfilesResponse\x12d\n" +
	"\rUpdateProfile\x12(.fontis.identity.v1.UpdateProfileRequest\x1a).fontis.identity.v1.UpdateProfileResponse\x12d\n" +
	"\rDeleteProfile\x12(.fontis.identity.v1.DeleteProfileRequest\x1a).fontis.identity.v1.DeleteProfileResponseB>Z<github.com/fontis-dev/fontis-platform/runtime/identity/protob\x06proto3"

var (
	file_identity_v1_identity_proto_rawDescOnce sync.Once
	file_identity_v1_identity_proto_rawDescData []byte
)

func file_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_identity_proto_rawDesc), len(file_identity_v1_identity_proto_rawDesc)))
	})
	return file_identity_v1_identity_proto_rawDescData
}

var file_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_identity_v1_identity_proto_goTypes = []any{
	(*Household)(nil),               // 0: fontis.identity.v1.Household
	(*Profile)(nil),                 // 1: fontis.identity.v1.Profile
	(*CreateHouseholdRequest)(nil),  // 2: fontis.identity.v1.CreateHouseholdRequest
	(*CreateHouseholdResponse)(nil), // 3: fontis.identity.v1.CreateHouseholdResponse
	(*GetHouseholdRequest)(nil),     // 4: fontis.identity.v1.GetHouseholdRequest
	(*GetHouseholdResponse)(nil),    // 5: fontis.identity.v1.GetHouseholdResponse
	(*UpdateHouseholdRequest)(nil),  // 6: fontis.identity.v1.UpdateHouseholdRequest
	(*UpdateHouseholdResponse)(nil), // 7: fontis.identity.v1.UpdateHouseholdResponse
	(*DeleteHouseholdRequest)(nil),  // 8: fontis.identity.v1.DeleteHouseholdRequest
	(*DeleteHouseholdResponse)(nil), // 9: fontis.identity.v1.DeleteHouseholdResponse
	(*ListHouseholdsRequest)(nil),   // 10: fontis.identity.v1.ListHouseholdsRequest
	(*ListHouseholdsResponse)(nil),  // 11: fontis.identity.v1.ListHouseholdsResponse
	(*CreateProfileRequest)(nil),    // 12: fontis.identity.v1.CreateProfileRequest
	(*CreateProfileResponse)(nil),   // 13: fontis.identity.v1.CreateProfileResponse
	(*GetProfileRequest)(nil),       // 14: fontis.identity.v1.GetProfileRequest
	(*GetProfileResponse)(nil),      // 15: fontis.identity.v1.GetProfileResponse
	(*ListProfilesRequest)(nil),     // 16: fontis.identity.v1.ListProfilesRequest
	(*ListProfilesResponse)(nil),    // 17: fontis.identity.v1.ListProfilesResponse
	(*UpdateProfileRequest)(nil),    // 18: fontis.identity.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),   // 19: fontis.identity.v1.UpdateProfileResponse
	(*DeleteProfileRequest)(nil),    // 20: fontis.identity.v1.DeleteProfileRequest
	(*DeleteProfileResponse)(nil),   // 21: fontis.identity.v1.DeleteProfileResponse
	(*timestamppb.Timestamp)(nil),   // 22: google.protobuf.Timestamp
}
var file_identity_v1_identity_proto_depIdxs = []int32{
	22, // 0: fontis.identity.v1.Household.created_at:type_name -> google.protobuf.Timestamp
	22, // 1: fontis.identity.v1.Household.updated_at:type_name -> google.protobuf.Timestamp
	22, // 2: fontis.identity.v1.Profile.created_at:type_name -> google.protobuf.Timestamp
	22, // 3: fontis.identity.v1.Profile.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: fontis.identity.v1.CreateHouseholdResponse.household:type_name -> fontis.identity.v1.Household
	0,  // 5: fontis.identity.v1.GetHouseholdResponse.household:type_name -> fontis.identity.v1.Household
	0,  // 6: fontis.identity.v1.UpdateHouseholdResponse.household:type_name -> fontis.identity.v1.Household
	0,  // 7: fontis.identity.v1.ListHouseholdsResponse.households:type_name -> fontis.identity.v1.Household
	1,  // 8: fontis.identity.v1.CreateProfileResponse.profile:type_name -> fontis.identity.v1.Profile
	1,  // 9: fontis.identity.v1.GetProfileResponse.profile:type_name -> fontis.identity.v1.Profile
	1,  // 10: fontis.identity.v1.ListProfilesResponse.profiles:type_name -> fontis.identity.v1.Profile
	1,  // 11: fontis.identity.v1.UpdateProfileResponse.profile:type_name -> fontis.identity.v1.Profile
	2,  // 12: fontis.identity.v1.IdentityService.CreateHousehold:input_type -> fontis.identity.v1.CreateHouseholdRequest
	4,  // 13: fontis.identity.v1.IdentityService.GetHousehold:input_type -> fontis.identity.v1.GetHouseholdRequest
	6,  // 14: fontis.identity.v1.IdentityService.UpdateHousehold:input_type -> fontis.identity.v1.UpdateHouseholdRequest
	8,  // 15: fontis.identity.v1.IdentityService.DeleteHousehold:input_type -> fontis.identity.v1.DeleteHouseholdRequest
	10, // 16: fontis.identity.v1.IdentityService.ListHouseholds:input_type -> fontis.identity.v1.ListHouseholdsRequest
	12, // 17: fontis.identity.v1.IdentityService.CreateProfile:input_type -> fontis.identity.v1.CreateProfileRequest
	14, // 18: fontis.identity.v1.IdentityService.GetProfile:input_type -> fontis.identity.v1.GetProfileRequest
	16, // 19: fontis.identity.v1.IdentityService.ListProfiles:input_type -> fontis.identity.v1.ListProfilesRequest
	18, // 20: fontis.identity.v1.IdentityService.UpdateProfile:input_type -> fontis.identity.v1.UpdateProfileRequest
	20, // 21: fontis.identity.v1.IdentityService.DeleteProfile:input_type -> fontis.identity.v1.DeleteProfileRequest
	3,  // 22: fontis.identity.v1.IdentityService.CreateHousehold:output_type -> fontis.identity.v1.CreateHouseholdResponse
	5,  // 23: fontis.identity.v1.IdentityService.GetHousehold:output_type -> fontis.identity.v1.GetHouseholdResponse
	7,  // 24: fontis.identity.v1.IdentityService.UpdateHousehold:output_type -> fontis.identity.v1.UpdateHouseholdResponse
	9,  // 25: fontis.identity.v1.IdentityService.DeleteHousehold:output_type -> fontis.identity.v1.DeleteHouseholdResponse
	11, // 26: fontis.identity.v1.IdentityService.ListHouseholds:output_type -> fontis.identity.v1.ListHouseholdsResponse
	13, // 27: fontis.identity.v1.IdentityService.CreateProfile:output_type -> fontis.identity.v1.CreateProfileResponse
	15, // 28: fontis.identity.v1.IdentityService.GetProfile:output_type -> fontis.identity.v1.GetProfileResponse
	17, // 29: fontis.identity.v1.IdentityService.ListProfiles:output_type -> fontis.identity.v1.ListProfilesResponse
	19, // 30: fontis.identity.v1.IdentityService.UpdateProfile:output_type -> fontis.identity.v1.UpdateProfileResponse
	21, // 31: fontis.identity.v1.IdentityService.DeleteProfile:output_type -> fontis.identity.v1.DeleteProfileResponse
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_identity_v1_identity_proto_init() }
func file_identity_v1_identity_proto_init() {
	if File_identity_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_identity_proto_rawDesc), len(file_identity_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_identity_v1_identity_proto_depIdxs,
		MessageInfos:      file_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_identity_v1_identity_proto = out.File
	file_identity_v1_identity_proto_goTypes = nil
	file_identity_v1_identity_proto_depIdxs = nil
}
