BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "fontis"
BBFILE_PATTERN_fontis = "^${LAYERDIR_RE}/"
BBFILE_PRIORITY_fontis = "10"

LAYERDEPENDS_fontis = "core openembedded-layer meta-security"
LAYERSERIES_COMPAT_fontis = "kirkstone scarthgap"
